#!/bin/sh /etc/rc.common

USE_PROCD=1
START=98
STOP=99

start_service() {
	config_load 'mqtt_sub'

	procd_open_instance
	procd_set_param command /usr/bin/mqtt_sub
	procd_set_param pidfile /var/run/mqtt_sub.pid
	procd_set_param file /etc/config/mqtt_sub
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "mqtt_sub"
	procd_open_trigger
		procd_add_config_trigger "config.change" "/etc/config/mqtt_sub" "mqtt_sub" reload
	procd_close_trigger
}



reload_service() {
	stop
	start
}